/*
 * OpenAPI Course
 * Specification for OpenAPI Course
 *
 * OpenAPI spec version: 1.0
 * Contact: john@springframework.guru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BeerOrderLine;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * BeerOrder
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-11-25T22:08:19.323Z[GMT]")
public class BeerOrder {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("customerId")
  private UUID customerId = null;

  @SerializedName("customerRef")
  private String customerRef = null;

  @SerializedName("beerOrderLines")
  private List<BeerOrderLine> beerOrderLines = null;

  @SerializedName("orderStatusCallbackUrl")
  private String orderStatusCallbackUrl = null;

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public UUID getId() {
    return id;
  }

  public BeerOrder customerId(UUID customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @Schema(required = true, description = "")
  public UUID getCustomerId() {
    return customerId;
  }

  public void setCustomerId(UUID customerId) {
    this.customerId = customerId;
  }

  public BeerOrder customerRef(String customerRef) {
    this.customerRef = customerRef;
    return this;
  }

   /**
   * Get customerRef
   * @return customerRef
  **/
  @Schema(description = "")
  public String getCustomerRef() {
    return customerRef;
  }

  public void setCustomerRef(String customerRef) {
    this.customerRef = customerRef;
  }

  public BeerOrder beerOrderLines(List<BeerOrderLine> beerOrderLines) {
    this.beerOrderLines = beerOrderLines;
    return this;
  }

  public BeerOrder addBeerOrderLinesItem(BeerOrderLine beerOrderLinesItem) {
    if (this.beerOrderLines == null) {
      this.beerOrderLines = new ArrayList<BeerOrderLine>();
    }
    this.beerOrderLines.add(beerOrderLinesItem);
    return this;
  }

   /**
   * Get beerOrderLines
   * @return beerOrderLines
  **/
  @Schema(description = "")
  public List<BeerOrderLine> getBeerOrderLines() {
    return beerOrderLines;
  }

  public void setBeerOrderLines(List<BeerOrderLine> beerOrderLines) {
    this.beerOrderLines = beerOrderLines;
  }

  public BeerOrder orderStatusCallbackUrl(String orderStatusCallbackUrl) {
    this.orderStatusCallbackUrl = orderStatusCallbackUrl;
    return this;
  }

   /**
   * Get orderStatusCallbackUrl
   * @return orderStatusCallbackUrl
  **/
  @Schema(description = "")
  public String getOrderStatusCallbackUrl() {
    return orderStatusCallbackUrl;
  }

  public void setOrderStatusCallbackUrl(String orderStatusCallbackUrl) {
    this.orderStatusCallbackUrl = orderStatusCallbackUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeerOrder beerOrder = (BeerOrder) o;
    return Objects.equals(this.id, beerOrder.id) &&
        Objects.equals(this.customerId, beerOrder.customerId) &&
        Objects.equals(this.customerRef, beerOrder.customerRef) &&
        Objects.equals(this.beerOrderLines, beerOrder.beerOrderLines) &&
        Objects.equals(this.orderStatusCallbackUrl, beerOrder.orderStatusCallbackUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, customerId, customerRef, beerOrderLines, orderStatusCallbackUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeerOrder {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    customerRef: ").append(toIndentedString(customerRef)).append("\n");
    sb.append("    beerOrderLines: ").append(toIndentedString(beerOrderLines)).append("\n");
    sb.append("    orderStatusCallbackUrl: ").append(toIndentedString(orderStatusCallbackUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
