/*
 * OpenAPI Course
 * Specification for OpenAPI Course
 *
 * OpenAPI spec version: 1.0
 * Contact: john@springframework.guru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.UUID;
/**
 * BeerOrderLine
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-11-25T22:08:19.323Z[GMT]")
public class BeerOrderLine {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("beerId")
  private UUID beerId = null;

  @SerializedName("upc")
  private String upc = null;

  @SerializedName("orderQuantity")
  private Integer orderQuantity = null;

  @SerializedName("quantityAllocated")
  private Integer quantityAllocated = null;

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public UUID getId() {
    return id;
  }

   /**
   * Get beerId
   * @return beerId
  **/
  @Schema(description = "")
  public UUID getBeerId() {
    return beerId;
  }

  public BeerOrderLine upc(String upc) {
    this.upc = upc;
    return this;
  }

   /**
   * Get upc
   * @return upc
  **/
  @Schema(required = true, description = "")
  public String getUpc() {
    return upc;
  }

  public void setUpc(String upc) {
    this.upc = upc;
  }

  public BeerOrderLine orderQuantity(Integer orderQuantity) {
    this.orderQuantity = orderQuantity;
    return this;
  }

   /**
   * Get orderQuantity
   * minimum: 1
   * maximum: 999
   * @return orderQuantity
  **/
  @Schema(required = true, description = "")
  public Integer getOrderQuantity() {
    return orderQuantity;
  }

  public void setOrderQuantity(Integer orderQuantity) {
    this.orderQuantity = orderQuantity;
  }

   /**
   * Get quantityAllocated
   * @return quantityAllocated
  **/
  @Schema(description = "")
  public Integer getQuantityAllocated() {
    return quantityAllocated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeerOrderLine beerOrderLine = (BeerOrderLine) o;
    return Objects.equals(this.id, beerOrderLine.id) &&
        Objects.equals(this.beerId, beerOrderLine.beerId) &&
        Objects.equals(this.upc, beerOrderLine.upc) &&
        Objects.equals(this.orderQuantity, beerOrderLine.orderQuantity) &&
        Objects.equals(this.quantityAllocated, beerOrderLine.quantityAllocated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, beerId, upc, orderQuantity, quantityAllocated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeerOrderLine {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    beerId: ").append(toIndentedString(beerId)).append("\n");
    sb.append("    upc: ").append(toIndentedString(upc)).append("\n");
    sb.append("    orderQuantity: ").append(toIndentedString(orderQuantity)).append("\n");
    sb.append("    quantityAllocated: ").append(toIndentedString(quantityAllocated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
