/*
 * OpenAPI Course
 * Specification for OpenAPI Course
 *
 * OpenAPI spec version: 1.0
 * Contact: john@springframework.guru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BeerOrder;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrderServiceApi
 */
@Ignore
public class OrderServiceApiTest {

    private final OrderServiceApi api = new OrderServiceApi();

    /**
     * 
     *
     * Place Order
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1CustomersCustomerIdOrdersPostTest() throws ApiException {
        UUID customerId = null;
        BeerOrder body = null;
        api.v1CustomersCustomerIdOrdersPost(customerId, body);

        // TODO: test validations
    }
}
